apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: verysecret
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: nonroot
  POSTGRES_NON_ROOT_PASSWORD: verysecret
