apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: cert-manager-values.yaml
    includeCRDs: true
  - name: nats
    repo: https://nats-io.github.io/k8s/helm/charts/
    releaseName: nats
    namespace: nats
    valuesFile: nats-values.yaml
    includeCRDs: true
resources:
  - certs.yaml
