issuer: http://dex:5556/dex

issuerRotation:
  - issuer: http://localhost:5556/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

staticClients:
  - id: logchef
    redirectURIs:
      - "http://localhost:8125/api/v1/auth/callback"
    name: "LogChef"
    secret: logchef-secret

oauth2:
  skipApprovalScreen: true

enablePasswordDB: true

staticPasswords:
  - email: "admin@logchef.internal"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

  - email: "demo@logchef.internal"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "demo-user"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5467"
