allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-singlereplica
parameters:
  protocol: nvmf
  repl: "1"
  nodeAffinityTopologyLabel: |
    zone: sgn
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Delete
volumeBindingMode: Immediate
