services:
  logchef:
    image: ghcr.io/mr-karan/logchef:latest
    container_name: logchef
    restart: on-failure
    ports:
      - "8125:8125"
    volumes:
      - ./configs/logchef.toml:/etc/logchef/config.toml:ro
      - logchef-data:/data
    depends_on:
      clickhouse:
        condition: service_healthy
      dex:
        condition: service_healthy
    networks:
      - logchef_net
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:8125/api/v1/health",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4
    container_name: clickhouse
    restart: on-failure
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./configs/clickhouse-config.xml:/etc/clickhouse-server/config.d/logchef.xml:ro
      - ./configs/clickhouse-users.xml:/etc/clickhouse-server/users.d/logchef.xml:ro
      - ./configs/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - clickhouse-data:/var/lib/clickhouse:delegated
      - clickhouse-logs:/var/log/clickhouse-server:delegated
    cap_add:
      - SYS_NICE
      - IPC_LOCK
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - logchef_net
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  dex:
    image: dexidp/dex:v2.35.3
    container_name: dex
    restart: on-failure
    ports:
      - "127.0.0.1:5556:5556"
    volumes:
      - ./configs/dex.yaml:/etc/dex/config.yaml:ro
      - dex-data:/var/dex
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    networks:
      - logchef_net
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5556/dex/.well-known/openid-configuration",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  vector:
    image: docker.io/timberio/vector:0.45.0-debian
    volumes:
      - ./configs/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      logchef:
        condition: service_healthy
    command: ["-c", "/etc/vector/vector.toml"]
    networks:
      - logchef_net

volumes:
  logchef-data:
  clickhouse-data:
  clickhouse-logs:
  dex-data:

networks:
  logchef_net:
    name: logchef_net
