version: "3"

services:
  nats:
    image: nats:latest
    container_name: nats
    network_mode: host
    command: --js --sd=/data
    volumes:
      - nats_data:/data # Persistent storage for JetStream data

volumes:
  nats_data:
